"""mig

Revision ID: 8d7fcef0d7e1
Revises: 3cff4be0e214
Create Date: 2022-12-26 09:08:11.113898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7fcef0d7e1'
down_revision = '3cff4be0e214'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
